### ISSUE TITLE
OOM Resource Exhausted after one epoch

### ISSUE THREAD

**Issue by giuliacern** [mnicnc404/CartoonGan-tensorflow#29]
Hi! I trained your model with Google Colab, and after an entire epoch of trained a get this error

`Traceback (most recent call last):
  File "train.py", line 707, in <module>
    main(**kwargs)
  File "train.py", line 645, in main
    t.train_gan()
  File "train.py", line 624, in train_gan
    (generator(val_real_batch, training=False) + 1) * 127.5, tf.uint8)
  File "/usr/local/envs/cartoongan/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 660, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/content/drive/My Drive/CartoonGan-tensorflow/generator.py", line 68, in call
    x = self.flat_conv1(x, training=training)
  File "/usr/local/envs/cartoongan/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 660, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/content/drive/My Drive/CartoonGan-tensorflow/layers.py", line 73, in call
    return self.model(x, training=training)
  File "/usr/local/envs/cartoongan/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 660, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/usr/local/envs/cartoongan/lib/python3.7/site-packages/tensorflow/python/keras/engine/sequential.py", line 256, in call
    outputs = layer(inputs, **kwargs)
  File "/usr/local/envs/cartoongan/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 660, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/usr/local/envs/cartoongan/lib/python3.7/site-packages/tensorflow/python/keras/layers/convolutional.py", line 196, in call
    outputs = self._convolution_op(inputs, self.kernel)
  File "/usr/local/envs/cartoongan/lib/python3.7/site-packages/tensorflow/python/ops/nn_ops.py", line 1078, in __call__
    return self.conv_op(inp, filter)
  File "/usr/local/envs/cartoongan/lib/python3.7/site-packages/tensorflow/python/ops/nn_ops.py", line 634, in __call__
    return self.call(inp, filter)
  File "/usr/local/envs/cartoongan/lib/python3.7/site-packages/tensorflow/python/ops/nn_ops.py", line 233, in __call__
    name=self.name)
  File "/usr/local/envs/cartoongan/lib/python3.7/site-packages/tensorflow/python/ops/nn_ops.py", line 1951, in conv2d
    name=name)
  File "/usr/local/envs/cartoongan/lib/python3.7/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 1031, in conv2d
    data_format=data_format, dilations=dilations, name=name, ctx=_ctx)
  File "/usr/local/envs/cartoongan/lib/python3.7/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 1130, in conv2d_eager_fallback
    ctx=_ctx, name=name)
  File "/usr/local/envs/cartoongan/lib/python3.7/site-packages/tensorflow/python/eager/execute.py", line 66, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[1117,256,256,96] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:Conv2D]`

I partially solved this issue by simply saving the checkpoints and weights before the end of the epoch and then retraining again, until the crash. 
Initially I thought that the model is too big, so I set up the batch size to 1, but still the problem persist. 
I think that there is a memory leak somewhere. Maybe at the end of the epoch you create new tensors or a copy of the entire model. I haven't checked yet but I'm going to update if I find something.

**Comment by zhiying8710** [comment]
do u have found something about this?

**Comment by giuliacern** [comment]
Yes. I commented this block of code in file train.py, starting from line 624 and the training proceeds without OOM error. 
Of course I don't realize the consequences on the elimination of the validation fake batch on the entire training.

`with summary_writer.as_default():
                if not self.disable_sampling:
                    val_fake_batch = tf.cast(
                        (generator(val_real_batch, training=False) + 1) * 127.5, tf.uint8)
                    img = np.expand_dims(self._save_generated_images(
                            val_fake_batch,
                            image_name=("gan_val_generated_images_at_epoch_"
                                       f"{epoch_idx}_step_{step}.png")),
                           0,
                    )
                    tf.summary.image('gan_val_generated_images', img, step=epoch)`

**Comment by zhiying8710** [comment]
ok, thx for ur anwser, i think may the `summary_writer.as_default()` is the cause, i'll try this solution.

**Comment by giuliacern** [comment]
Why do you think `summary_writer.as_default()` is the cause?

**Comment by CodTan** [comment]
@giuliacern, removing the LOCs you mentioned didn't help me. Instead I reduced the number of `batch_size`, and it did the trick!

**Comment by giuliacern** [comment]
Where were you running the experiments?

**Comment by CodTan** [comment]
Windows 7
Spyder 3.3.6
Python 3.7.4

**Comment by fantasy-fish** [comment]
> @giuliacern, removing the LOCs you mentioned didn't help me. Instead I reduced the number of `batch_size`, and it did the trick!

But would reducing batch_size downgrade the model performance?

**Comment by mnicnc404** [comment]
We suggest using gpu with more than 11GB memory. If you encounter OOM issues, try reducing `batch_size`, `input_size`, or `d_base_filters` and `base_filters` in `train.py`. 

We don't have unlimited computing power so apparently we cannot try all possible hyper-parameter combinations; therefore we cannot guarantee the model performance if you change any of the default hyper-parameters. It's very likely that you get worse model performance when you are forced to change any of the hyper-parameters due to lack of memory, and we are sorry that we cannot do much with this issue.
